version: '3.8'

services:
  php:
    build: .
    container_name: app
    volumes:
      - ./src:/var/www/html
      - ./docker/configs/laravel-application/.env:/var/www/html/.env
      - vendor:/var/www/html/vendor
    ports:
      - "84:80"
    networks:
      - task-management
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-management-db
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    networks:
      - task-management

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - db
    networks:
      - task-management

volumes:
  vendor:

networks:
  task-management:
    driver: bridge